name: API Actions

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    env:
      API_DIR: ./api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.WORKING_DIR }}
      - name: Run tests
        run: npm run test
        working-directory: ${{ env.WORKING_DIR }}